services:
  - type: web
    name: kfc-live
    runtime: static
    rootDir: ""
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: ALLOWALL
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Content-Security-Policy
        value: "frame-ancestors *"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
